apiVersion: v1
data:
    DOMAIN_LOCAL: ENC[AES256_GCM,data:++PgiS9CeZ1L3cfN0EjdFXb+LLYC/Qx1blLi,iv:urzvOqU/TjmdQdU382aWnIB0dceRe7QDzkDPI6Osx3E=,tag:iUkTxvFNfMhXXgX6IevS1Q==,type:str]
    DOMAIN_PUBLIC: ENC[AES256_GCM,data:DLRmWRZ1mf7Ku2dAne4=,iv:yoPzEGpq4u7Zfw4SXZJwNukD9X5WEFAoEiLEu4n62/s=,tag:u6vyp9FduSSzEyQnE48cTA==,type:str]
    EMAIL_ADDRESS: ENC[AES256_GCM,data:Br333AhAOQaaIknojQL5,iv:pwSYbTLuSGhUHhCG5dt/0aONCYq/6kKtpJhb4AysyaQ=,tag:envdO8FfskRxj17SDo2LQg==,type:str]
    METALLB_ADDRESS: ENC[AES256_GCM,data:bT6oUkV1/bQ3rNM=,iv:3nUaXu6X2BkWXZQFEGiXmKMff+CroSkEvfiWXlyjQkI=,tag:fUTY6Cd8PYENiX5GXrTOng==,type:str]
    NETWORK: ENC[AES256_GCM,data:iZ68zkB/CVkZ0i+0,iv:43oPJjS6O7lSwnQQnlXsERRrxJT4DoJX5nAsfhSc7ps=,tag:KV18olpNQESHX3Agz0FnrA==,type:str]
    NETWORK_DMZ: ENC[AES256_GCM,data:Fss7CegtIj7A4OTavA==,iv:xLjdbHTQDQx4o4ZRto/RsU65NFj10lzRWpr+ZvvrEOc=,tag:vui2RgpaBogSpQ9y/E0WBw==,type:str]
    NETWORK_INFRA: ENC[AES256_GCM,data:Glyb/7dC80eURbcaVg==,iv:PYejzRJrniCX1aLWAE1LLYwIksXtj030ib7XJiZvoe4=,tag:5g7sdoXazUdvmw19TcWOTA==,type:str]
    NETWORK_SERVER: ENC[AES256_GCM,data:JR0J3xxAykqB9KTp2A==,iv:xTPR0TnVjdQwRY1FIiNhPkRi5s0gLxXbyWVT8oLp/eo=,tag:hbimmkad1mGtgP0cr0g8KA==,type:str]
    NETWORK_IOT: ENC[AES256_GCM,data:gdSfxGFRiCDgRSBEmA==,iv:Atm6xNHkBs4qMUxbK+8Uqyi6Bks2jbvK4OLbF2sAFOA=,tag:rjO4V8MTPJxQfx66WY7tDA==,type:str]
    NETWORK_GUEST: ENC[AES256_GCM,data:5BB/4WgFGcVf2VehkBjQ,iv:q6OZwxgcZJBTGEpw7AuL5T2JfDqzGlz3hzP5bomMSRA=,tag:K7VYx6I8cmquk2HvpAC8Dg==,type:str]
    NETWORK_USER: ENC[AES256_GCM,data:Zzla1WFOEEWLxBBsQg==,iv:M6zdZOGd4XcVTjjghM32hHvljvi1rjqfx8oY9kvPRe0=,tag:3qpvcgPBK4dRowAkqdrRCA==,type:str]
    ROUTER_IP: ENC[AES256_GCM,data:Ae90JHXmVXqCaQ==,iv:x+1KdOVIpwFlALGx7zE0t2iSI9ssCezWuJr+T3hbENE=,tag:1VWlBD9SdB42y27WWRIeeg==,type:str]
    SITE: ENC[AES256_GCM,data:r4qfz4fa,iv:iYusE1ycAOF7O6bH1oFWssEPAaqqst7vcs69zZiEH+w=,tag:az+9sxu3Kd/h0WrrT1/TaA==,type:str]
    TZ: ENC[AES256_GCM,data:jicT0NQMyTq8CBvfdMS/,iv:t08lNJvMEQ4fSSpyB/BR4/+0uDyGbQ+uZHeaWBotrZ0=,tag:ZVBmr+2pIzMDH3PM1GPy9Q==,type:str]
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: environment
    namespace: flux-system
sops:
    lastmodified: "2025-12-25T14:26:59Z"
    mac: ENC[AES256_GCM,data:vq2/O74p8r4C0kBmg7CvF1H1pSV9ptPPrMUH7ybvA4X0Oc5UKGP2Wz+hKW5SeYAWOdv3hA8PqFBdqSuWJQbvtreZA6nIdSJuLEgzH/FKF2azgrRuuYOWRYqFnVHlhFxtrnyHWACvf7U4wl/U0vsVYfTBZUdItW8hM52eVZ3ua4Y=,iv:8Mkw5624t+KMv4a3ekc8WOcV8F65kdZpn5GTAgWwW6o=,tag:ySywosnDK5Y4ily2f9Z4bg==,type:str]
    pgp:
        - created_at: "2023-01-19T20:00:32Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/2zKbmHCsRnAQ//aixZXa2wpZagyqeNn2ahnuXiePUvNb5RbBrUQLOSiPrP
            kf3SrpXlKPVhGLXmjnVE7XRU8/+K3aV4YHC5hzu7ecN++SRaVvYStPB+ZW0KGabo
            lKjLRY+h1zwQQ1uVGYFKmKWSwULPdnSPW6+OjKSgHF6lVcIpxlflS+EnuDPAgGtK
            Ol5wvcVnmMBCr1wPAslLNEnw+PuHc+CMEi6QeNovcDNyqFo9AqXT1eCjSXMqgXzj
            /P/UzwlQJLSP9CReKfAyEMPBxDcFxPRySI6/Nyko0loLZd0o3UsI018odlF+dscZ
            AjIdsB5IQVbVf2eG6TZY7d2ewvfrw/7Ztat1XFbW/obqKY6DcKxO6Zouu8uLix6j
            4PLxadVqj2x+EnbjgVsdEwueSWGWNhMU2uZVHg24Ln/VDPf2h1c1tp9DsDtA+36G
            l25qzGALy2GvJc2H77XZrS2KkXiIIcIamTfzbhPwAHNpt8LHWZcu6zyFkxqO7Ttt
            CRFNBX0i8NclnwUG9PZhbKndXKkMXVUCBwqM6CJHEnV2ul7DF7TCTh5mPteL2LsH
            Wm3HVuFb6ozWcc+ViEXmI+DqCReh97HyOz5QZ0Jlbrwuj8t/9AYA/O12hHLiYLY0
            tjukjbNw60Bk+Xr6ReJkrMWnASKCuX2oGbLCtuabN0w8toDU2wkSsId8E5bYkFfS
            XAHFmixJC3Oa6sgtp7FZ4FvjEa3PHOOrDJ6U4YFFL/bXeTAqsud9Ja9+ysntKxlY
            U35Upa6vC9asQflU11a4nSDy+ZG6sco0uKBX9qAbZB3bqSp7kWBGOwFvt9R9
            =ANsz
            -----END PGP MESSAGE-----
          fp: 976AA83A5066FFE4CF485376F76C07C5F5BB0BEB
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
