---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: dmz-ipwhitelist
  namespace: media

spec:
  ipWhiteList:
    sourceRange:
      - 127.0.0.1/32
      - ${NETWORK_DMZ}
      - ${NETWORK_INFRA}
      - ${NETWORK_USER}
      - ${NETWORK_SERVER}
