---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - repository.yaml
  - certificates.yaml
  - release.yaml
  - middleware.yaml
  - ingress.yaml
  - alerts.yaml
  - image-updates.yaml
